---

- hosts: all
  become: true
  pre_tasks:
  
  
  - name: install updates (CentOS) 
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"


  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  
- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages for Ubuntu 
    tags: webserver,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: install httpd and php packages for Centos
    tags: webserver,httpd,centos
    yum:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"


- hosts: db_servers
  become: true
  tasks:
   
  - name: install mariadb package (CentOS)
    tags: db,mariadb,centos
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    tags: db,ubuntu,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package 
    tags: samba
    package:
      name: samba
      state: latest







